name: CyanMessages
main: ga.cyanoure.cyanmessages.Main
version: 1.1
author: Cyanoure
permissions:
    cyanmessages.private:
        default: true
        children:
            cyanmessages.*: true
    cyanmessages.helpop.send:
        default: true
        children:
            cyanmessages.*: true
            cyanmessages.helpop.*: true
    cyanmessages.helpop.receive:
        default: false
        children:
            cyanmessages.*: true
            cyanmessages.helpop.*: true